name: Deploy to server via ftp
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE
      - run: npm install
      - name: build application
        run: npm run build
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: nandoerni.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "build/"
          server-dir: "winti-gayes/"
